dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- name: jhipapp
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: jxapp
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.63
- name: soda-gift
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
