dependencies:
- name: demo1001
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- name: soda-gift
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: sodagift-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
